// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file and ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Ensure proper logout behavior
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      // Add flow type for better compatibility
      flowType: 'pkce',
      // Add debug mode for troubleshooting (disabled to reduce console noise)
      debug: false,
    },
    // Add global configuration for better error handling
    global: {
      headers: {
        'X-Client-Info': 'infra-fix-citizen',
        // Add Accept header to fix 406 Not Acceptable errors
        'Accept': 'application/json',
        // Prevent caching of API responses in PWA
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
      },
    },
    // Add realtime configuration
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);
