// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file and ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Ensure proper logout behavior
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      // Add flow type for better compatibility
      flowType: 'pkce',
      // Add debug mode for troubleshooting
      debug: import.meta.env.DEV,
      // Ensure proper redirect handling
      redirectTo: typeof window !== 'undefined' ? window.location.origin : undefined,
    },
    // Add global configuration for better error handling
    global: {
      headers: {
        'X-Client-Info': 'infra-fix-citizen',
        'X-Requested-With': 'XMLHttpRequest',
      },
    },
    // Add realtime configuration
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);
