// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suasdgighpwmxgiuefvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1YXNkZ2lnaHB3bXhnaXVlZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjEwODUsImV4cCI6MjA2NTAzNzA4NX0.qe73NKkiikIyDtnXElW0RqZ56o_W0fCc6TsUApaYAq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);